### ISSUE TITLE
debug mode not working on debian7

### ISSUE THREAD

**Issue by chqrly** [unix-thrust/beurk#79]

**Comment by nil0x42** [comment]
after verification, this is completely normal, and it will work this way on any target system.
according to the API odcumentation (https://github.com/unix-thrust/beurk/wiki/API-Documentation), debug level can only be set at compile time.

NOTE: BEURK_DEBUG_FILE can be use to redirect debug messages to a file different than /dev/stderr, for example, it can be set to /dev/null in order to disable debug.
